Repository materialsproject/atomate2, pull requests merged in 2023-10, with the labels that each got.

#540 Remove `__all__` from all modules
  src/atomate2/amset/files.py
  src/atomate2/amset/jobs.py
  src/atomate2/amset/run.py
  src/atomate2/amset/schemas.py
  src/atomate2/common/analysis/elastic.py
  src/atomate2/common/files.py
  src/atomate2/common/jobs/defect.py
  src/atomate2/common/jobs/phonons.py
  src/atomate2/common/jobs/utils.py
  src/atomate2/common/schemas/cclib.py
  src/atomate2/common/schemas/elastic.py
  src/atomate2/common/schemas/phonons.py
  src/atomate2/cp2k/drones.py
  src/atomate2/cp2k/files.py
  src/atomate2/cp2k/flows/core.py
  src/atomate2/cp2k/jobs/base.py
  src/atomate2/cp2k/jobs/core.py
  src/atomate2/cp2k/run.py
  src/atomate2/cp2k/schemas/calculation.py
  src/atomate2/cp2k/schemas/task.py
  src/atomate2/cp2k/sets/base.py
  src/atomate2/cp2k/sets/core.py
  src/atomate2/forcefields/flows/phonons.py
  src/atomate2/forcefields/jobs.py
  src/atomate2/lobster/files.py
  src/atomate2/lobster/jobs.py
  src/atomate2/lobster/run.py
  src/atomate2/lobster/schemas.py
  src/atomate2/settings.py
  src/atomate2/utils/datetime.py
  src/atomate2/utils/file_client.py
  src/atomate2/utils/log.py
  src/atomate2/utils/path.py
  src/atomate2/vasp/drones.py
  src/atomate2/vasp/files.py
  src/atomate2/vasp/flows/amset.py
  src/atomate2/vasp/flows/core.py
  src/atomate2/vasp/flows/elastic.py
  src/atomate2/vasp/flows/elph.py
  src/atomate2/vasp/flows/lobster.py
  src/atomate2/vasp/flows/phonons.py
  src/atomate2/vasp/jobs/amset.py
  src/atomate2/vasp/jobs/base.py
  src/atomate2/vasp/jobs/core.py
  src/atomate2/vasp/jobs/defect.py
  src/atomate2/vasp/jobs/elastic.py
  src/atomate2/vasp/jobs/elph.py
  src/atomate2/vasp/jobs/lobster.py
  src/atomate2/vasp/run.py
  src/atomate2/vasp/schemas/defect.py
  src/atomate2/vasp/schemas/elph.py
  src/atomate2/vasp/sets/base.py
  src/atomate2/vasp/sets/core.py
Labels: ecosystem, house-keeping, breaking, pkg

#550 Fix wrong INCAR values in MP workflows
  src/atomate2/vasp/files.py
  src/atomate2/vasp/jobs/mp.py
  tests/test_data/lobster/lobsteroutputs/mp-2534/POTCAR.gz
  tests/test_data/lobster/lobsteroutputs/mp-754354/POTCAR.gz
  tests/test_data/vasp/Si_mp_gga_relax/GGA_Relax_1/outputs/POTCAR.gz
  tests/test_data/vasp/Si_mp_gga_relax/GGA_Relax_2/outputs/POTCAR.gz
  tests/test_data/vasp/Si_mp_gga_relax/GGA_Static/outputs/POTCAR.gz
  tests/test_data/vasp/Si_mp_meta_gga_relax/pbesol_pre_relax/inputs/INCAR
  tests/test_data/vasp/Si_mp_meta_gga_relax/r2scan_final_static/inputs/INCAR
  tests/test_data/vasp/Si_mp_meta_gga_relax/r2scan_relax/inputs/INCAR
  tests/test_data/vasp/Si_old_double_relax/outputs/POTCAR.gz
Labels: testing, fix, mp

#558 Fix failing tests from Pydantic v2 migration
  src/atomate2/common/schemas/defects.py
  src/atomate2/common/schemas/phonons.py
  src/atomate2/cp2k/schemas/calculation.py
  src/atomate2/cp2k/schemas/task.py
  src/atomate2/lobster/schemas.py
  tests/forcefields/test_jobs.py
Labels: testing, fix, version

#560 Add Aaron Kaplan and Matthew McDermott to `contributors.md`
  docs/about/contributors.md
Labels: documentation

#381 Document architectural difference between atomate 1 and 2
  docs/user/atomate-1-vs-2.md
Labels: documentation

#551 Check full INCAR by default in `mock_vasp` fixture
  src/atomate2/amset/schemas.py
  src/atomate2/common/schemas/cclib.py
  src/atomate2/cp2k/run.py
  src/atomate2/cp2k/schemas/task.py
  src/atomate2/cp2k/sets/base.py
  src/atomate2/lobster/run.py
  src/atomate2/lobster/schemas.py
  src/atomate2/vasp/jobs/defect.py
  src/atomate2/vasp/run.py
  src/atomate2/vasp/sets/base.py
  tests/forcefields/test_jobs.py
  tests/test_data/vasp/Si_hse_optics/hse_optics/inputs/INCAR
  tests/test_data/vasp/Si_hse_optics/hse_static/inputs/INCAR
  tests/vasp/conftest.py
Labels: testing

#568 Add Thomas Purcell to `contributors.md`
  docs/about/contributors.md
Labels: documentation

#567 Update to Pydantic v2
  .github/workflows/testing.yml
  pyproject.toml
  src/atomate2/amset/schemas.py
  src/atomate2/common/flows/defect.py
  src/atomate2/common/jobs/defect.py
  src/atomate2/common/jobs/phonons.py
  src/atomate2/common/jobs/utils.py
  src/atomate2/common/schemas/cclib.py
  src/atomate2/common/schemas/defects.py
  src/atomate2/common/schemas/elastic.py
  src/atomate2/common/schemas/phonons.py
  src/atomate2/cp2k/schemas/calculation.py
  src/atomate2/cp2k/schemas/task.py
  src/atomate2/forcefields/schemas.py
  src/atomate2/forcefields/utils.py
  src/atomate2/lobster/schemas.py
  src/atomate2/settings.py
  src/atomate2/vasp/run.py
  src/atomate2/vasp/sets/base.py
  src/atomate2/vasp/sets/core.py
  tests/common/schemas/test_cclib.py
  tests/common/test_jobs.py
  tests/forcefields/test_jobs.py
  tests/vasp/flows/test_defect.py
  tests/vasp/flows/test_phonons.py
  tests/vasp/jobs/test_core.py
  tests/vasp/lobster/schemas/test_lobster.py
  tests/vasp/schemas/test_defect.py
Labels: dependencies, ecosystem, pkg

#532 Add MatPES GGA and r2SCAN static makers
  .github/workflows/testing.yml
  ADMIN.md
  pyproject.toml
  src/atomate2/vasp/flows/matpes.py
  src/atomate2/vasp/flows/mp.py
  src/atomate2/vasp/jobs/matpes.py
  src/atomate2/vasp/jobs/mp.py
  src/atomate2/vasp/sets/matpes.py
  src/atomate2/vasp/sets/mp.py
  tests/test_data/vasp/matpes_pbe_r2scan_flow/pbe_static/inputs/INCAR
  tests/test_data/vasp/matpes_pbe_r2scan_flow/pbe_static/inputs/POSCAR
  tests/test_data/vasp/matpes_pbe_r2scan_flow/pbe_static/inputs/POTCAR.spec
  tests/test_data/vasp/matpes_pbe_r2scan_flow/pbe_static/outputs/CONTCAR.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/pbe_static/outputs/DOSCAR.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/pbe_static/outputs/EIGENVAL.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/pbe_static/outputs/IBZKPT.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/pbe_static/outputs/INCAR.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/pbe_static/outputs/INCAR.orig.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/pbe_static/outputs/OSZICAR.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/pbe_static/outputs/OUTCAR.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/pbe_static/outputs/PCDAT.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/pbe_static/outputs/POSCAR.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/pbe_static/outputs/POSCAR.orig.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/pbe_static/outputs/PROCAR.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/pbe_static/outputs/REPORT.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/pbe_static/outputs/WAVECAR.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/pbe_static/outputs/XDATCAR.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/pbe_static/outputs/custodian.json.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/pbe_static/outputs/std_err.txt
  tests/test_data/vasp/matpes_pbe_r2scan_flow/pbe_static/outputs/vasp.out.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/pbe_static/outputs/vasprun.xml.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/r2scan_static/inputs/INCAR
  tests/test_data/vasp/matpes_pbe_r2scan_flow/r2scan_static/inputs/POSCAR
  tests/test_data/vasp/matpes_pbe_r2scan_flow/r2scan_static/inputs/POTCAR.spec
  tests/test_data/vasp/matpes_pbe_r2scan_flow/r2scan_static/outputs/CONTCAR.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/r2scan_static/outputs/DOSCAR.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/r2scan_static/outputs/EIGENVAL.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/r2scan_static/outputs/IBZKPT.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/r2scan_static/outputs/INCAR.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/r2scan_static/outputs/INCAR.orig.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/r2scan_static/outputs/OSZICAR.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/r2scan_static/outputs/OUTCAR.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/r2scan_static/outputs/PCDAT.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/r2scan_static/outputs/POSCAR.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/r2scan_static/outputs/POSCAR.orig.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/r2scan_static/outputs/PROCAR.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/r2scan_static/outputs/REPORT.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/r2scan_static/outputs/WAVECAR.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/r2scan_static/outputs/XDATCAR.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/r2scan_static/outputs/custodian.json.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/r2scan_static/outputs/std_err.txt
  tests/test_data/vasp/matpes_pbe_r2scan_flow/r2scan_static/outputs/vasp.out.gz
  tests/test_data/vasp/matpes_pbe_r2scan_flow/r2scan_static/outputs/vasprun.xml.gz
  tests/vasp/flows/test_matpes.py
  tests/vasp/jobs/test_matpes.py
Labels: enhancement, ecosystem, mp

#575 Add @matthewkuner to contributors
  docs/about/contributors.md
Labels: documentation

#574 `parse_additional_json()` ignore `FW.json.gz` in output directories
  src/atomate2/common/utils.py
  tests/test_data/vasp/Si_mp_meta_gga_relax/r2scan_relax/outputs/FW.json.gz
Labels: testing, fix, mp

#553 Fix `bandgap_tol` and delete `bandgap_override` on `MPMetaGGARelaxSetGenerator`
  src/atomate2/settings.py
  src/atomate2/vasp/sets/base.py
  src/atomate2/vasp/sets/mp.py
  tests/common/test_settings.py
  tests/test_data/vasp/Si_mp_gga_relax/GGA_Relax_1/inputs/INCAR
  tests/test_data/vasp/Si_mp_gga_relax/GGA_Relax_2/inputs/INCAR
  tests/test_data/vasp/Si_mp_gga_relax/GGA_Static/inputs/INCAR
  tests/test_data/vasp/Si_mp_meta_gga_relax/pbesol_pre_relax/inputs/INCAR
  tests/test_data/vasp/Si_mp_meta_gga_relax/r2scan_final_static/inputs/INCAR
  tests/test_data/vasp/Si_mp_meta_gga_relax/r2scan_relax/inputs/INCAR
  tests/vasp/flows/test_mp.py
  tests/vasp/jobs/test_mp.py
Labels: fix, mp

#576 Fix `VaspInputGenerator`'s `_set_kspacing` not respecting `auto_ismear = False` nor `auto_kspacing = False`
  .pre-commit-config.yaml
  src/atomate2/forcefields/utils.py
  src/atomate2/vasp/flows/mp.py
  src/atomate2/vasp/sets/base.py
  src/atomate2/vasp/sets/matpes.py
  src/atomate2/vasp/sets/mp.py
  tests/test_data/vasp/Si_mp_gga_relax/GGA_Relax_1/inputs/INCAR
  tests/test_data/vasp/Si_mp_meta_gga_relax/pbesol_pre_relax/inputs/INCAR
  tests/test_data/vasp/matpes_pbe_r2scan_flow/r2scan_static/inputs/INCAR
  tests/vasp/conftest.py
  tests/vasp/flows/test_matpes.py
  tests/vasp/flows/test_mp.py
  tests/vasp/jobs/test_matpes.py
Labels: fix, vasp

#561 Clean up VASP powerups, correct params in MP flows, test for `_set_u_params`, test for `_set_kspacing`, fix `_get_incar` method of `VaspInputSet`
  src/atomate2/vasp/powerups.py
  src/atomate2/vasp/sets/base.py
  tests/vasp/test_sets.py
Labels: testing, fix, house-keeping

#580 Future type annotations
  .pre-commit-config.yaml
  pyproject.toml
  src/atomate2/amset/schemas.py
  src/atomate2/cp2k/schemas/calculation.py
  src/atomate2/forcefields/jobs.py
  src/atomate2/settings.py
  src/atomate2/vasp/sets/base.py
  tests/cp2k/conftest.py
  tests/vasp/conftest.py
  tests/vasp/flows/test_phonons.py
  tests/vasp/lobster/conftest.py
Labels: ux, pkg, types, qa

#582 Use `numpy.testing.assert_allclose` over assert `np.(all|is)close`
  src/atomate2/cli/dev.py
  src/atomate2/cp2k/schemas/calc_types/utils.py
  tests/forcefields/flows/test_phonon.py
  tests/vasp/flows/test_elastic.py
  tests/vasp/flows/test_elph.py
  tests/vasp/flows/test_phonons.py
  tests/vasp/jobs/test_core.py
  tests/vasp/lobster/schemas/test_lobster.py
Labels: testing, dx

#586 Change `MatPesGGAPlusMetaGGAStaticMaker.output` to dict containing both statics
  pyproject.toml
  src/atomate2/common/schemas/elastic.py
  src/atomate2/cp2k/flows/core.py
  src/atomate2/cp2k/run.py
  src/atomate2/lobster/run.py
  src/atomate2/vasp/flows/core.py
  src/atomate2/vasp/flows/matpes.py
  src/atomate2/vasp/run.py
  tests/vasp/flows/test_matpes.py
  tests/vasp/flows/test_mp.py
  tests/vasp/flows/test_phonons.py
  tests/vasp/jobs/test_matpes.py
  tests/vasp/jobs/test_mp.py
Labels: testing, mp

#594 Breaking: default `Atomate2Settings.VASP_INHERIT_INCAR` to `False`
  src/atomate2/settings.py
  src/atomate2/vasp/jobs/matpes.py
  src/atomate2/vasp/sets/mp.py
  tests/test_data/vasp/Si_hse_optics/hse_optics/inputs/INCAR
Labels: ux, breaking, mp, vasp

#596 Test MP + MatPES set generators
  src/atomate2/vasp/sets/mp.py
  tests/common/schemas/test_cclib.py
  tests/cp2k/jobs/test_core.py
  tests/forcefields/flows/test_elastic.py
  tests/forcefields/flows/test_phonon.py
  tests/forcefields/test_jobs.py
  tests/vasp/flows/test_phonons.py
  tests/vasp/jobs/test_matpes.py
  tests/vasp/jobs/test_mp.py
  tests/vasp/lobster/schemas/test_lobster.py
  tests/vasp/sets/test_matpes.py
  tests/vasp/sets/test_mp.py
  tests/vasp/test_sets.py
Labels: testing, fix, mp

#597 Move most test imports from function into module scope
  tests/common/schemas/test_cclib.py
  tests/common/schemas/test_defect.py
  tests/common/schemas/test_elastic.py
  tests/common/test_files.py
  tests/common/test_jobs.py
  tests/common/test_settings.py
  tests/conftest.py
  tests/forcefields/flows/test_elastic.py
  tests/forcefields/flows/test_phonon.py
  tests/forcefields/test_jobs.py
  tests/vasp/conftest.py
  tests/vasp/flows/test_core.py
  tests/vasp/flows/test_defect.py
  tests/vasp/flows/test_elastic.py
  tests/vasp/flows/test_elph.py
  tests/vasp/flows/test_mp.py
  tests/vasp/flows/test_phonons.py
  tests/vasp/jobs/test_core.py
  tests/vasp/jobs/test_mp.py
  tests/vasp/lobster/conftest.py
  tests/vasp/lobster/schemas/test_lobster.py
  tests/vasp/schemas/test_defect.py
  tests/vasp/test_drones.py
  tests/vasp/test_files.py
  tests/vasp/test_powerups.py
Labels: testing, house-keeping, qa

#593 Breaking: Unify previous directory `Maker` API
  src/atomate2/amset/jobs.py
  src/atomate2/common/flows/defect.py
  src/atomate2/common/flows/elastic.py
  src/atomate2/common/jobs/defect.py
  src/atomate2/common/jobs/phonons.py
  src/atomate2/common/utils.py
  src/atomate2/cp2k/flows/core.py
  src/atomate2/cp2k/jobs/base.py
  src/atomate2/cp2k/jobs/core.py
  src/atomate2/forcefields/jobs.py
  src/atomate2/vasp/flows/amset.py
  src/atomate2/vasp/flows/core.py
  src/atomate2/vasp/flows/elastic.py
  src/atomate2/vasp/flows/elph.py
  src/atomate2/vasp/flows/lobster.py
  src/atomate2/vasp/flows/matpes.py
  src/atomate2/vasp/flows/mp.py
  src/atomate2/vasp/flows/phonons.py
  src/atomate2/vasp/jobs/amset.py
  src/atomate2/vasp/jobs/base.py
  src/atomate2/vasp/jobs/core.py
  src/atomate2/vasp/jobs/elph.py
  src/atomate2/vasp/jobs/lobster.py
Labels: enhancement, discussion, breaking

#599 Add keyword `incar_exclude: Sequence[str] = None` to `fake_run_vasp()`
  src/atomate2/vasp/flows/matpes.py
  tests/test_data/vasp/matpes_pbe_r2scan_flow/pbe_static/inputs/INCAR
  tests/vasp/conftest.py
  tests/vasp/flows/test_matpes.py
  tests/vasp/jobs/test_matpes.py
Labels: enhancement, testing, mp
