Repository materialsproject/atomate2, pull requests merged in 2023-09, with the labels that each got.

#506 Enforce magmom precedence in INCAR creation
  src/atomate2/vasp/sets/base.py
  tests/vasp/test_sets.py
Labels: fix

#514 Add StructureMetadata as baseclass for output documents
  src/atomate2/common/schemas/elastic.py
  src/atomate2/common/schemas/phonons.py
  src/atomate2/lobster/schemas.py
  src/atomate2/vasp/schemas/elph.py
  tests/vasp/flows/test_elastic.py
  tests/vasp/flows/test_elph.py
  tests/vasp/flows/test_phonons.py
  tests/vasp/lobster/schemas/test_lobster.py
Labels: enhancement

#516 Update @arosen93 to @Andrew-S-Rosen
  CHANGELOG.md
  docs/about/contributors.md
Labels: documentation, house-keeping

#522 Warn on empty config
  src/atomate2/settings.py
  tests/common/test_settings.py
Labels: testing, fix
