Repository materialsproject/atomate2, pull requests merged in 2024-02, with the labels that each got.

#600 Add `KspacingMetalHandler` to VASP `_DEFAULT_HANDLERS`
  pyproject.toml
  src/atomate2/vasp/run.py
  tests/vasp/test_base.py
Labels: fix, error handling

#725 Fix docstring on `MatPesMetaGGAStaticSetGenerator`
  src/atomate2/vasp/sets/matpes.py
Labels: documentation

#728 Print invalid value and list valid ones in `PhononMaker` error messages
  .pre-commit-config.yaml
  src/atomate2/common/files.py
  src/atomate2/common/schemas/cclib.py
  src/atomate2/cp2k/schemas/calc_types/utils.py
  src/atomate2/cp2k/schemas/calculation.py
  src/atomate2/cp2k/sets/base.py
  src/atomate2/forcefields/flows/phonons.py
  src/atomate2/lobster/schemas.py
  src/atomate2/utils/file_client.py
  src/atomate2/vasp/files.py
  src/atomate2/vasp/flows/phonons.py
  src/atomate2/vasp/sets/base.py
  tests/common/schemas/test_defect.py
  tests/common/test_files.py
  tests/cp2k/sets/test_core.py
  tests/vasp/flows/test_phonons.py
Labels: fix, ux, qa

#729 Define `MLFF` `Enum` to ensure consistent force field names
  src/atomate2/common/jobs/defect.py
  src/atomate2/common/jobs/elastic.py
  src/atomate2/common/jobs/phonons.py
  src/atomate2/common/schemas/cclib.py
  src/atomate2/common/schemas/elastic.py
  src/atomate2/common/schemas/phonons.py
  src/atomate2/forcefields/__init__.py
  src/atomate2/forcefields/flows/relax.py
  src/atomate2/forcefields/jobs.py
  src/atomate2/forcefields/schemas.py
  src/atomate2/lobster/schemas.py
  src/atomate2/vasp/flows/md.py
  src/atomate2/vasp/jobs/amset.py
  src/atomate2/vasp/jobs/defect.py
  src/atomate2/vasp/jobs/elph.py
  src/atomate2/vasp/jobs/lobster.py
  src/atomate2/vasp/schemas/elph.py
  tests/vasp/flows/test_phonons.py
  tests/vasp/jobs/test_md.py
  tests/vasp/schemas/test_defect.py
Labels: enhancement, mlff

#731 Add `citation.cff` file, Zenodo record and readme "How to cite" section
  CHANGELOG.md
  README.md
  citation.cff
  tests/vasp/test_sets.py
Labels: documentation
