Repository materialsproject/atomate2, pull requests merged in 2024-10, with the labels that each got.

#1004 Allow energy minimization maker to report energies
  src/atomate2/openmm/jobs/base.py
  src/atomate2/openmm/jobs/core.py
  tests/openmm_md/flows/test_core.py
  tests/openmm_md/jobs/test_base.py
  tests/openmm_md/jobs/test_core.py
  tests/openmm_md/jobs/test_generate.py
Labels: enhancement, md

#1005 Fix aims phonon flow test
  tests/aims/test_flows/test_phonon_workflow.py
Labels: testing, fix, phonon

#1009 Fix `ruff` PLC0206
  .pre-commit-config.yaml
  src/atomate2/ase/utils.py
  src/atomate2/common/flows/eos.py
  src/atomate2/common/jobs/gruneisen.py
  src/atomate2/common/schemas/phonons.py
  src/atomate2/cp2k/schemas/calculation.py
Labels: linting
