Repository materialsproject/atomate2, pull requests merged in 2024-11, with the labels that each got.

#1053 Add trajectory reporter to openmm workflow
  src/atomate2/openmm/jobs/base.py
  src/atomate2/openmm/utils.py
  tests/openmm_md/jobs/test_core.py
  tests/openmm_md/test_utils.py
Labels: enhancement, md

#1047 Minor docs cleanup
  docs/user/codes/openmm.md
  docs/user/codes/vasp-workflows.csv
  docs/user/codes/vasp.md
Labels: docs

#1064 Fix `generate_phonon_displacements` magmom removal side effect
  .pre-commit-config.yaml
  pyproject.toml
  src/atomate2/ase/schemas.py
  src/atomate2/common/flows/qha.py
  src/atomate2/common/jobs/electrode.py
  src/atomate2/common/jobs/phonons.py
  src/atomate2/forcefields/schemas.py
  tests/vasp/test_sets.py
Labels: fix
