Repository materialsproject/atomate2, pull requests merged in 2024-01, with the labels that each got.

#663 Enable all `ruff` rules by default
  docs/conf.py
  pyproject.toml
  src/atomate2/amset/run.py
  src/atomate2/amset/schemas.py
  src/atomate2/cli/dev.py
  src/atomate2/common/flows/elastic.py
  src/atomate2/common/jobs/defect.py
  src/atomate2/common/schemas/defects.py
  src/atomate2/cp2k/drones.py
  src/atomate2/cp2k/run.py
  src/atomate2/cp2k/schemas/calculation.py
  src/atomate2/cp2k/schemas/task.py
  src/atomate2/cp2k/sets/base.py
  src/atomate2/forcefields/flows/elastic.py
  src/atomate2/forcefields/schemas.py
  src/atomate2/forcefields/utils.py
  src/atomate2/lobster/run.py
  src/atomate2/lobster/schemas.py
  src/atomate2/settings.py
  src/atomate2/utils/file_client.py
  src/atomate2/vasp/drones.py
  src/atomate2/vasp/flows/elastic.py
  src/atomate2/vasp/flows/matpes.py
  src/atomate2/vasp/jobs/core.py
  src/atomate2/vasp/run.py
  src/atomate2/vasp/sets/base.py
  tests/conftest.py
  tests/forcefields/flows/test_phonon.py
  tests/forcefields/test_utils.py
  tests/vasp/flows/test_defect.py
  tests/vasp/schemas/test_defect.py
  tests/vasp/test_sets.py
Labels: qa

#651 Mark schema fields with `None` default as `Optional` to pass pydantic v2 validation
  pyproject.toml
  src/atomate2/common/schemas/cclib.py
  src/atomate2/common/schemas/defects.py
  src/atomate2/common/schemas/elastic.py
  src/atomate2/common/schemas/phonons.py
  tests/common/schemas/test_cclib.py
  tests/common/schemas/test_defect.py
  tests/common/schemas/test_elastic.py
  tests/common/schemas/test_phonons.py
Labels: testing, fix, schema

#489 Multi step MD flow
  src/atomate2/vasp/flows/core.py
  src/atomate2/vasp/flows/md.py
  src/atomate2/vasp/jobs/core.py
  src/atomate2/vasp/jobs/md.py
  src/atomate2/vasp/schemas/md.py
  src/atomate2/vasp/sets/base.py
  src/atomate2/vasp/sets/core.py
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_1/inputs/INCAR
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_1/inputs/KPOINTS
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_1/inputs/POSCAR
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_1/inputs/POTCAR.spec
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_1/outputs/CONTCAR.gz
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_1/outputs/INCAR.gz
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_1/outputs/INCAR.orig.gz
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_1/outputs/KPOINTS.gz
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_1/outputs/KPOINTS.orig.gz
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_1/outputs/OUTCAR.gz
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_1/outputs/POSCAR.gz
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_1/outputs/POSCAR.orig.gz
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_1/outputs/POTCAR.spec
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_1/outputs/custodian.json.gz
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_1/outputs/vasprun.xml.gz
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_2/inputs/INCAR
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_2/inputs/KPOINTS
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_2/inputs/POSCAR
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_2/inputs/POTCAR.spec
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_2/outputs/CONTCAR.gz
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_2/outputs/INCAR.gz
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_2/outputs/INCAR.orig.gz
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_2/outputs/KPOINTS.gz
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_2/outputs/KPOINTS.orig.gz
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_2/outputs/OUTCAR.gz
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_2/outputs/POSCAR.gz
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_2/outputs/POSCAR.orig.gz
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_2/outputs/POTCAR.spec
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_2/outputs/custodian.json.gz
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_2/outputs/vasprun.xml.gz
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_3/inputs/INCAR
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_3/inputs/KPOINTS
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_3/inputs/POSCAR
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_3/inputs/POTCAR.spec
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_3/outputs/CONTCAR.gz
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_3/outputs/INCAR.gz
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_3/outputs/INCAR.orig.gz
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_3/outputs/KPOINTS.gz
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_3/outputs/KPOINTS.orig.gz
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_3/outputs/OUTCAR.gz
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_3/outputs/POSCAR.gz
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_3/outputs/POSCAR.orig.gz
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_3/outputs/POTCAR.spec
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_3/outputs/custodian.json.gz
  tests/test_data/vasp/Si_multi_md/molecular_dynamics_3/outputs/vasprun.xml.gz
  tests/vasp/flows/test_md.py
  tests/vasp/jobs/test_core.py
  tests/vasp/jobs/test_md.py
Labels: enhancement

#669 Set `extra="allow"` on `PhononBSDOSDoc`
  src/atomate2/common/schemas/phonons.py
  tests/common/schemas/test_elastic.py
  tests/common/schemas/test_phonons.py
  tests/vasp/flows/test_phonons.py
Labels: enhancement, ux, phonon, schema

#670 Revert dependency on `ase` to PyPI release but install from `main` branch in CI
  .github/workflows/deploy.yml
  .github/workflows/docs.yml
  .github/workflows/testing.yml
  .pre-commit-config.yaml
  pyproject.toml
Labels: fix, pkg

#690 Prep for next `pymatgen` release
  src/atomate2/vasp/sets/base.py
  tests/cp2k/conftest.py
  tests/vasp/lobster/schemas/test_lobster.py
Labels: fix, version
